config/routes.rb
Rails.application.routes.draw do
	
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

	resources :restaurants do 
		resources :reviews
	end

	resources :reviews do 
		resources :endorsements
	end

  root 'restaurants#index'

end

app/models/endorsement.rb
class Endorsement < ActiveRecord::Base
  belongs_to :review
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :reviews, dependent: :destroy
	validates :name, length: {minimum: 3, message: ": please create a longer name"}, uniqueness: true

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png",
									  :storage => :s3, 
									  :s3_credentials => Proc.new{|a| a.instance.s3_credentials }

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	def average_rating
    return 'N/A' if reviews.none?
    reviews.average(:rating)
	end

  def s3_credentials
    {:bucket => "yelpmb", :access_key_id => Rails.application.secrets.aws_access_key_id, :secret_access_key => Rails.application.secrets.aws_secret_access_key}
  end
  
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :restaurant
	validates :rating, inclusion: (1..5)
	has_many :endorsements
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook, :twitter]

  def self.find_for_facebook_oauth(auth)
	  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	    user.email = auth.info.email
	    user.password = Devise.friendly_token[0,20]
	    user.name = auth.info.name   # assuming the user model has a name
	    user.image = auth.info.image # assuming the user model has an image
	  end
	end

def self.find_for_twitter_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    if user
      return user
    else
      registered_user = User.where(:email => auth.uid + "@twitter.com").first
      if registered_user
        return registered_user
      else
        user = User.create(name:auth.extra.raw_info.name,
                            provider:auth.provider,
                            uid:auth.uid,
                            email:auth.uid+"@twitter.com",
                            password:Devise.friendly_token[0,20],
                          )
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController
	include ActionView::Helpers::TextHelper
	def create
    @review = Review.find(params[:review_id])
    @review.endorsements.create
    render json: {new_endorsement_count: "#{pluralize(@review.endorsements.count, "endorsement")}"}
	end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

	def index
		@restaurants = Restaurant.all
	end

	def new
	  @restaurant = Restaurant.new
	end

	def create
		@restaurant = Restaurant.create(params[:restaurant].permit(:name, :image, :description, :location, :postcode))
		if @restaurant.save	
			redirect_to restaurants_path
		else
			render 'new'
		end
	end

	def edit
	  @restaurant = Restaurant.find(params[:id])
	end

	def show
	  @restaurant = Restaurant.find(params[:id])
	end

	def update
	  @restaurant = Restaurant.find(params[:id])
	  @restaurant.update(params[:restaurant].permit(:name, :image, :description, :location, :postcode))
	  redirect_to restaurants_path
	end

	def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    flash[:notice] = "Restaurant deleted successfully"
    redirect_to restaurants_path
	end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new 
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.create(params[:review].permit(:rating, :thoughts))
    if @review.save
	    redirect_to restaurants_path
		else
			render 'new'
		end
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter
    auth = env["omniauth.auth"]

    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)
    if @user.persisted?
    	flash[:notice] = I18n.t "devise.omniauth_callbacks.success"
    	sign_in_and_redirect @user, :event => :authentication
    else
    	session["devise.twitter_uid"] = request.env["omniauth.auth"]
    	redirect_to new_user_registration_url
    end
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
	def star_rating(rating)
    return rating unless rating.respond_to? (:round)
    remainder = (5 - rating.round)
    '★' * rating.round + ('☆' * remainder)
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset='utf-8'>
  <title>YelpClone</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=DroidSans' rel='stylesheet' type='text/css'>
</head>
<body>

<% if user_signed_in? %>
  Signed in as <%= current_user.name %>. Not you?
  <%= link_to "Sign out", destroy_user_session_path, method::delete %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path %>
  <%= link_to "Sign in", new_user_session_path %>
<% end %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

</body>
</html>

app/views/restaurants/_form.html.erb
<% if @restaurant.errors.any? %>
	<div id='errors_explanation'>
		<h2>
			<%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved: 
		</h2>
		<ul>
			<% @restaurant.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<%= form_for @restaurant, :html => { :multipart => true } do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
  <%= f.label :image %>
  <%= f.file_field :image %>
	<%= f.label :description %>
	<%= f.text_field :description %>
	<%= f.label :location %>
	<%= f.text_field :location %>
	<%= f.label :postcode %>
	<%= f.text_field :postcode %>
	<%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<%= render 'form' %>

app/views/restaurants/index.html.erb
<% if@restaurants.any? %>
  <% @restaurants.each do |restaurant| %>
    <%= image_tag restaurant.image.url(:thumb) %>
    <h2><a href="<%= restaurant_path(restaurant) %>"><%= restaurant.name %></a></h2>
    <%= link_to "Edit #{restaurant.name}",
						    edit_restaurant_path(restaurant) %>
    <%= link_to "Delete #{restaurant.name}",
						    restaurant_path(restaurant), 
						    method: :delete %>
	  <%= link_to "Review #{restaurant.name}",
						    new_restaurant_review_path(restaurant) %>
		<ul>
      <% restaurant.reviews.each do |review| %>
	      <li>
	        <%= "#{review.thoughts}" %> 
	        <%= star_rating(review.rating) %>
	        <span class="italicise">posted: <%= time_ago_in_words(review.created_at) %> ago</span>
	        <%= link_to 'Endorse this review', review_endorsements_path(review), class: 'endorsements-link' %>
	        <span class='endorsements_count'>
	        	<%= pluralize(review.endorsements.count, 'endorsement') %>
	        </span>
	      </li>
      <% end %>
		</ul>
		<h3>Average rating: <%= star_rating(restaurant.average_rating) %></h3>
  <% end %>
<% else %>
  No restaurants yet
<% end %>
<p>
	<%= link_to 'Add a restaurant', new_restaurant_path %>
</p>

app/views/restaurants/new.html.erb
<%= render 'form' %>

app/views/restaurants/show.html.erb
<%= image_tag @restaurant.image.url(:medium) %> 

<h2><%= @restaurant.name %></h2>
<p><%= @restaurant.description %></p>

<h3>Reviews</h3>
<ul>
  <% @restaurant.reviews.each do |review| %>
    <li>
      <%= "#{review.thoughts}" %> 
      <%= star_rating(review.rating) %>
    </li>
    <span class="italicise">posted: <%= time_ago_in_words(review.created_at) %> ago</span>
  <% end %>
</ul>

<h3>Location</h3>
<p><%= @restaurant.location %>, <%= @restaurant.postcode %></p>

<% if @restaurant.lat && @restaurant.long %>
	<div id="map"></div>
	<div class='lat' style='display:none'><%= @restaurant.lat %></div>
	<div class='lng' style='display:none'><%= @restaurant.long %></div>
<% end %>

<div><%= link_to "Go back", restaurants_path %></div>

app/views/reviews/new.html.erb
<% if @review.errors.any? %>
	<div id='errors_explanation'>
		<h2>
			<%= pluralize(@review.errors.count, "error") %> prohibited this rating from being saved: 
		</h2>
		<ul>
			<% @review.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<%= form_for [@restaurant, @review] do |f| %>
	<%= f.label :thoughts %>
	<%= f.text_area :thoughts %>

	<%= f.label :rating %>
	<%= f.select :rating, (1..5) %>
	<%= f.submit 'Leave review' %>
<% end %>